server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/arbanware
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    open-in-view: false
  messages:
    basename: message,errors
  thymeleaf:
    c


logging:
  level:
    org.hibernate.SQL: debug
